version: '3.8'

services:
  db:
    image: postgres:13
    container_name: insurance_db
    environment:
      POSTGRES_USER: insurance_username
      POSTGRES_PASSWORD: insurance_password
      POSTGRES_DB: insurance
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./insurance-api
    container_name: insurance_api
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: insurance_username
      DATABASE_PASSWORD: insurance_password
      DATABASE_NAME: insurance
    ports:
      - "3001:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./insurance-frontend
    container_name: insurance_frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db_data:
