version: '3.8'

services:
  db:
    image: postgres:13
    container_name: insurance_db
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: insurance
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./insurance-api
    container_name: insurance_api
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: your_username
      DATABASE_PASSWORD: your_password
      DATABASE_NAME: insurance
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
